### ISSUE TITLE
Flickering spec

### ISSUE THREAD

**Issue by amoose** [amoose/coaster-app#13]
https://s3.amazonaws.com/archive.travis-ci.org/jobs/137864487/log.txt?deansi=true

```
Failures:

  1) UsersController POST create with permitted params creates a user
     [31mFailure/Error: [0m[32mif[0m @current_user [32mand[0m @current_user.ip_address != request.remote_ip [32mand[0m @current_user.geolocation.updated_at < [1;34m1[0m.hour.ago[0m
     [31m[0m
     [31mNoMethodError:[0m
     [31m  undefined method `<' for nil:NilClass[0m
     [36m# ./app/helpers/sessions_helper.rb:9:in `current_user='[0m
     [36m# ./app/helpers/sessions_helper.rb:4:in `sign_in'[0m
     [36m# ./app/controllers/users_controller.rb:22:in `create'[0m
     [36m# ./spec/controllers/users_controller_spec.rb:34:in `block (5 levels) in <top (required)>'[0m
     [36m# ./spec/controllers/users_controller_spec.rb:33:in `block (4 levels) in <top (required)>'[0m

Finished in 52.3 seconds (files took 2.09 seconds to load)
[31m29 examples, 1 failure[0m

Failed examples:

[31mrspec ./spec/controllers/users_controller_spec.rb:32[0m [36m# UsersController POST create with permitted params creates a user[0m

Coverage report generated for RSpec to /home/travis/build/amoose/coaster-app/coverage. 241 / 373 LOC (64.61%) covered.
/home/travis/.rvm/rubies/ruby-2.3.1/bin/ruby -I/home/travis/build/amoose/coaster-app/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.4.4/lib:/home/travis/build/amoose/coaster-app/vendor/bundle/ruby/2.3.0/gems/rspec-support-3.4.1/lib /home/travis/build/amoose/coaster-app/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.4.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed

travis_time:end:02cd8604:start=1466011796807600553,finish=1466011853345264833,duration=56537664280
[0K
[31;1mThe command "bundle exec rake" exited with 1
```

**Comment by amoose** [comment]
https://gist.github.com/amoose/5998bc1f47795d979c8624b748ae5519

**Comment by amoose** [comment]
I haven't seen this in a while. Closing.
